### ISSUE TITLE
report

### ISSUE THREAD

**Issue by XITRIX** [jenisov/kjoin#1]
Запустил сервис, клиент и сервер на трёх виртуальных машинах объединённых в локальную сеть, работоспособность подтверждена и запечатлена в скриншоте "report2.png"

**Comment by jenisov** [comment]
Да вижу.

Твоя ошибка: report закоммичен в ветку master, надо складывать все отчеты в собственные ветки.

**Comment by Vovkasquid** [comment]
Сделал новую ветку, запушил туда свой скришнот, где 3 виртуальные машины выполнили тестовый пример.
Только не знаю, что делать дальше. Нужен какой-нибудь материал на почитать.
